### ISSUE TITLE
xserver

### ISSUE THREAD

**Issue by Jianningli** [edsaac/streamlit-PyVista-viewer#12]
Hi,
great project. However, i encounter some issues recently using stpyvista.

Locally, it runs well.  But when deployed to a server, the 3D model fails to display on the browser on the user end, with the following error:

'this system does not appear to be running an xserver
PyVista will likely segfault when rendering.
Try starting a virtual frame buffer with xvfb, or using

  ``pyvista.start_xvfb()``
  warnings.warn(

It is strange that some time ago (before update?), the 3D viewer works fine

**Comment by edsaac** [comment]
I'd assume you are deploying on a headless environment, so you can add this line to the beginning of your python script to create a "virtual framebuffer"

```python
pyvista.start_xvfb()
``` 

Also, you will need to have installed `xvfb` and `libgl1-mesa-glx`. On Debian:

```bash
apt install libgl1-mesa-dev xvfb
```

**********
Check: 
- https://docs.pyvista.org/api/utilities/_autosummary/pyvista.start_xvfb.html
- https://docs.pyvista.org/user-guide/jupyter/panel.html#configuration-considerations

**Comment by Jianningli** [comment]
> 
Hi,

Thanks for the fast reply.

It works after adding pyvista.start_xvfb() and the libgl1-mesa-dev & xvfb packages.
